### ISSUE TITLE
environment meaning in yalm file is not clear.

### ISSUE THREAD

**Issue by FPSychotic** [AIS-Bonn/rviz_cinematographer#13]
Hi, I'm setting a mid-360, more or less I have clear the settings  but I cannot find how "environment" works.
Also in the Avia file there is different options than Velodyne one.

I would thank more detailed explanations or a config file for mid-360 if possible, couldn't find the vertical angular resolution, horizontal is <0.15 which doesn't look very precise info, I added that 0.15 to vertical and horizontal resolution.

Thank by share this software , there is very smart and clever things here.

I will happy in give .bags and test anything to help if needed.

**Comment by Razlaw** [comment]
Hi, this repo has nothing to do with Velodyne or Avia sensors. 
It's just about creating trajectories for the rviz camera and recording videos in rviz. 
I guess you wanted to post this issue somewhere else.

Thank you for the positive feedback though - in case it was meant for me ;)

**Comment by FPSychotic** [comment]
> Hi, this repo has nothing to do with Velodyne or Avia sensors. It's just about creating trajectories for the rviz camera and recording videos in rviz. I guess you wanted to post this issue somewhere else.
> 
> Thank you for the positive feedback though - in case it was meant for me ;)

Ohhh, sorry yes , I pasted in your github by error. Ahha, apologies by that.
But yes, after discovered your RViz tool , tell you that is amazing, and a great idea, I couldn't imagine would be anything like this. So yes, congratulations, and your other repositories looks amazing too.
Thanks by share, God bless you
