### ISSUE TITLE
Build fails in install mode

### ISSUE THREAD

**Issue by cellard0or** [AIS-Bonn/rviz_cinematographer#3]
When building in install mode, video_recorder_nodelet is not found and the build fails. I guess this is due to missing INSTALL directives in the video_recorder CMakeLists.txt.

**Comment by Razlaw** [comment]
Thanks for reporting the issue :) 

I just build the packages in a fresh workspace using catkin tools in install mode without any problems. 

Could you provide more details to you setup so I can recreate the problem? 
E.g. ros version, build tool, workspace settings (like how you invoke install mode), error message

**Comment by cellard0or** [comment]
Thanks for looking into it! Here are some details:
Using Ros Melodic. I ran this script to reproduce the issue:
`mkdir -p /tmp/test/src`
`cd /tmp/test/src`
`git clone https://github.com/AIS-Bonn/rviz_cinematographer.git`
`cd ..`
`catkin init`
`catkin config --install`
`catkin b`

Error message:
> Project 'rviz_cinematographer_gui' tried to find library
  'video_recorder_nodelet'.  The library is neither a target nor
  built/installed properly.  Did you compile project 'video_recorder'? Did
  you find_package() it before the subdirectory containing its code is
  included?

Interestingly, it works fine in devel mode.

**Comment by Razlaw** [comment]
Now everything should run as expected. 

In your script to have to 

`source /opt/ros/melodic/setup.bash`

before building for the first time. 

And 

`source /tmp/test/install/setup.bash`

after building and before launching the cinematographer using 

`roslaunch rviz_cinematographer_gui rviz_cinematographer_gui.launch`

Just for the sake of completeness.

**Comment by cellard0or** [comment]
Indeed, I forgot to add the source commands.
The fix works fine, thanks a lot. Very nice tool!
