### ISSUE TITLE
can the camera trajectory be extended to Gazebo?

### ISSUE THREAD

**Issue by ljburtz** [AIS-Bonn/rviz_cinematographer#5]
Hello and thank you for making this package: the cinematographic trajectory builder makes for pro-like videos!

Is there a way to use that same camera trajectory for controlling the user_camera in gazebo's own GUI? (extend what happens in RVIZ to Gazebo?)

Thanks a lot for any pointers!
Louis

**Comment by Razlaw** [comment]
Thanks :) 

I'm sorry, there is no option to do that. 
My experiences with gazebo are very limited. 
You could simulate a camera sensor in gazebo and publish the resulting image to generate a video. 
This should be a tutorial for that use case: 

[http://gazebosim.org/tutorials?tut=camera_save&cat=sensors](url)

And this is an example of how to simulate a moving object or the camera in your case:

[http://gazebosim.org/tutorials?tut=actor&cat=build_robot#Scriptedtrajectories](url)

The "Scripted Trajectories" chapter should be enough to get you started. 

But I don't know whether gazebo offers some kind of interactive markers to specify trajectories. 

If you make a tool for that, send me a link and I will spread the word ;)

**Comment by ljburtz** [comment]
thanks for the prompt answer and confirmation! Will reopen if I ever do start working on such a tool!

**Comment by Razlaw** [comment]
I'm not sure how much that helps but there was a video at the current ROS World about a package called robot cinematics. 
It's a package to create animation videos in gazebo worlds. 

This is a link to the video:
[https://vimeo.com/480572957](url)

Their git repo linked in the video description is currently empty, so I don't know if this is what you are looking for.

**Comment by ljburtz** [comment]
thanks for the link! will keep an eye open on that too
